library(RODBC)

# conexion con la bd
ch <- odbcConnect("Teradata", uid = "jvelezve", pwd = "Jimnyjb74")

# nombre de la tabla
tabla <- "PRO_SK_DATA_V.V_GT23_F341_SOL1"

# estadistica descriptiva (por tipo de acreditado)
consulta <- paste0(
  "SELECT FECHA_INFORMACION,",
  " CASE WHEN CAST(FECHA_INFORMACION - 19000000 AS DATE) - CAST(FECHA_INICIAL_DEL_CREDITO - 19000000 AS DATE)  < 90 THEN 'NUEVO' ELSE 'RECURRENTE' END,",
  " COUNT(*) AS N_REG,",
  " SUM(SALDO_CAPITAL) AS CAPITAL,",
  " SUM(SALDO_INTERESES) AS INTERESES,",
  " SUM(VALOR_GARANTIA) AS GARANTIA,",
  " AVG(TASA_PROMEDIO_DEL_CREDITO) AS TASA_CREDITO,",
  " SUM(TASA_PROMEDIO_DEL_CREDITO * SALDO_CAPITAL) / SUM(SALDO_CAPITAL) AS TASA_CREDITO_PONDERADA",
  " FROM ", tabla,
  " WHERE CAST(FECHA_INICIAL_DEL_CREDITO AS INTEGER) BETWEEN 19600101 AND 20231231",
  " GROUP BY FECHA_INFORMACION, (CASE WHEN CAST(FECHA_INFORMACION - 19000000 AS DATE) - CAST(FECHA_INICIAL_DEL_CREDITO - 19000000 AS DATE) < 90 THEN 'NUEVO' ELSE 'RECURRENTE' END)"
)

res_tipo_acreditado <- sqlQuery(ch, consulta)

# estadistica descriptiva (por CIIU)
consulta <- paste0(
  "SELECT FECHA_INFORMACION,",
  " SUBSTRING(CAST(CIIU AS VARCHAR(12)), 1, 4),",
  " COUNT(*) AS N_REG,",
  " SUM(SALDO_CAPITAL) AS CAPITAL,",
  " SUM(SALDO_INTERESES) AS INTERESES,",
  " SUM(VALOR_GARANTIA) AS GARANTIA,",
  " AVG(TASA_PROMEDIO_DEL_CREDITO) AS TASA_CREDITO,",
  # " SUM(TASA_PROMEDIO_DEL_CREDITO * SALDO_CAPITAL) / SUM(SALDO_CAPITAL) AS TASA_CREDITO_PONDERADA",
  " SUM(TASA_PROMEDIO_DEL_CREDITO * SALDO_CAPITAL) / NULLIF(SUM(SALDO_CAPITAL), 0) AS TASA_CREDITO_PONDERADA",
  " FROM ", tabla,
  " WHERE CAST(FECHA_INICIAL_DEL_CREDITO AS INTEGER) BETWEEN 19600101 AND 20231231",
  # " AND SALDO_CAPITAL > 0"
  " GROUP BY FECHA_INFORMACION, SUBSTRING(CAST(CIIU AS VARCHAR(12)), 1, 4)"
)

res_ciiu <- sqlQuery(ch, consulta)
